pagination was implemented
ArturNagaycev/tt_ukad_spa_react_ts_sass pull request #2
Opened 2023-02-22 15:49 UTC by ArturNagaycev

[DEMO link](https://arturnagaycev.github.io/tt_ukad_spa_react_ts_sass/)

2023-02-23 10:34 UTC, dmytro-mashchenko commented on src/components/Pagination/Pagination.tsx
> +
Is this check is required if you already disabled button? (67 line of this document)

2023-02-23 11:00 UTC, dima0208 approved these changes

2023-02-24 11:41 UTC, IgorNovikov10 requested changes

2023-02-24 11:41 UTC, IgorNovikov10 commented on src/components/Pagination/Pagination.tsx
> +  const getPages = (pagesNumber: number) => {
move this function outside of the Pagination component as it's static and does not depend on any state/props

2023-02-24 11:41 UTC, IgorNovikov10 commented on src/components/Pagination/Pagination.tsx
> +      {getPages(LAST_PAGE_NUMBER).map((page, index) => (
I would suggest to rename LAST_PAGE_NUMBER to TOTAL_PAGES_NUMBER to make it clearer what this number is, but it's up to you

2023-02-24 11:41 UTC, IgorNovikov10 commented on src/components/Slider/Slider.tsx
> +    dispatch(fetchProducts(1));
it's better to define default property value (1) in the `fetchProducts` function instead of passing it from the place where it's used

2023-02-24 12:17 UTC, IgorNovikov10 approved these changes

2023-02-24 12:18 UTC, merged